### PR TITLE
Added accumulated exclusive and start/stop trace cmd

### PR DESCRIPTION
**Pull request by honkstar1**
* Added accumulated exclusive column which is very useful when doing optimizations over large codebases.
* Added CompileScore.StartTrace and CompileScore.StopTrace commands that makes it possible to integrate start/stop/produce compile scores into custom build systems used inside visual studio (Unreal for example has its own build system)

### CODE REVIEW

**Comment by Viladoman** [comment]
Thanks for the PR! That's sweet. I really appreciate it. 
I might need to accommodate the accumulated exclusive to some local changes I have moving forward. 
In general it looks good.

**Comment by honkstar1** [comment]
Perfect, thank you. I've added so UnrealVS (Unreal's visual studio plugin) can build single file through unreal's build system and profile using Compile score.. it is a sweet workflow for reducing include dependencies.

**Comment by Viladoman** [comment]
I would like to still integrate your PR and then I can adapt whatever on top. 

I am really interested on your usage of the new commands with UnrealVS. 
Sadly I am not super familiar with Unreal, would it be possible to write a small text on how to use it so I we can add it to our wiki page here? 

Thanks for your support.

**Comment by honkstar1** [comment]
Lol, I thought "close" was the same as handing it over to you... I am a total n00b when it comes to github 🤣 

I would really appreciate if you could pull it in to main.

Unreal has its own build tool (not using msbuild etc). when building projects visual studio just run a cmd line through the NMAKE api which hands the work over to the custom build tool.

Most of the time when building unreal (and games on top of unreal) you are using "unity" files. They go under many names and are essentially a cpp that includes 30-50 other cpp files.

However, now and then you want to build an individual file (or in compile score's case output the include graph which is super awesome).. and to do that we need to add additional options to this nmake cmd line. The way we are doing it is through a visual studio extension called UnrealVS.

What I did was extending that so before we call our cmd line which starts the build of one file I call 
UnrealVSPackage.Instance.DTE.ExecuteCommand("CompileScore.StartTrace");
.. and when compile is done I call
UnrealVSPackage.Instance.DTE.ExecuteCommand("CompileScore.StopTrace");

and everything pops up in visual studio the way you want it to. It is really nice.

Btw, here's unreal on github: https://github.com/EpicGames/UnrealEngine

We have been integrating include-what-you-use into the build system too which is cool. I've used it to clean up includes in 25000+ files in unreal/fortnite. We are doing a big push in compile times and are currently working with microsoft vs devs to get "header units" working in unreal :-)

**Pull request merged**
